version: "3.9"

services:
  db:
    image: postgres:14
    container_name: nevup_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nevup
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: nevup_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nevup
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: nevup_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"